### ISSUE TITLE
Tips for taking frames with iPhone

### ISSUE THREAD

**Issue by HowoongJun** [spla-tam/SplaTAM#12]
Hi, thank you for your support. 

Is there any tips for taking frames with iPhone? (overlapping, angle.. etc)
I ran your work with online mode \w iPhone 13 pro but the result is not very good enough. 

Thank you

**Comment by Nik-V9** [comment]
Hi, in its current version, the DDS drops frame in between due to the high resolution. This can cause large motion between frames, leading to insufficient time for convergence.

We found that moving the camera slowly while sending the captures for the online demo is good. This is similar to some of the guidelines used by popular apps such as Luma AI or Polycam:
https://docs.lumalabs.ai/MCrGAEukR4orR9
