### ISSUE TITLE
Discrepancies in Generated PLY File and Rendered Images

### ISSUE THREAD

**Issue by NithinJangid** [spla-tam/SplaTAM#92]
I’ve been working with the generated PLY files and have observed a few issues that I’d like to bring to your attention.

Firstly, I noticed that the generated PLY files lack the f_rest property. This is unlike the original Gaussian splatting PLY files which do include this property. Could you please explain why this discrepancy exists?

Secondly, I’ve found that the quality of the rendered images is not up to par. The images appear to be of poor quality. Could you provide some insight into why this might be happening?

![0018](https://github.com/spla-tam/SplaTAM/assets/54679456/cb879782-1280-46e4-b7b6-e66e46ce97b4)
![0006](https://github.com/spla-tam/SplaTAM/assets/54679456/8a16ff58-f166-4969-ac36-5beeb0d616e8)

**Comment by Nik-V9** [comment]
Hi, Thanks for trying out our code!

Re. First Question: I'm unsure what the `f_rest` property is in the ply file of 3DGS. Could you provide more details?

Currently, our code base converts our custom format outputs to ply. This was a feature added in this pull request from other contributors: https://github.com/spla-tam/SplaTAM/pull/78

Re. Second Question: I believe you are seeing bad performance due to floater Gaussians initialized at the wrong depth. This is a problem I've also encountered, especially with the iPhone depth for larger-scale scenes. The iPhone depth has artifacts where it bins out the depth at an arbitrary max value. 

Currently, SplaTAM strongly relies on depth; we will have an update on that soon.
